
package pe.edu.upeu.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SueldoImpService", targetNamespace = "http://ws.upeu.edu.pe/", wsdlLocation = "http://localhost:9091/soap/sueldo?wsdl")
public class SueldoImpService
    extends Service
{

    private final static URL SUELDOIMPSERVICE_WSDL_LOCATION;
    private final static WebServiceException SUELDOIMPSERVICE_EXCEPTION;
    private final static QName SUELDOIMPSERVICE_QNAME = new QName("http://ws.upeu.edu.pe/", "SueldoImpService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9091/soap/sueldo?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SUELDOIMPSERVICE_WSDL_LOCATION = url;
        SUELDOIMPSERVICE_EXCEPTION = e;
    }

    public SueldoImpService() {
        super(__getWsdlLocation(), SUELDOIMPSERVICE_QNAME);
    }

    public SueldoImpService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SUELDOIMPSERVICE_QNAME, features);
    }

    public SueldoImpService(URL wsdlLocation) {
        super(wsdlLocation, SUELDOIMPSERVICE_QNAME);
    }

    public SueldoImpService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SUELDOIMPSERVICE_QNAME, features);
    }

    public SueldoImpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SueldoImpService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SueldoDao
     */
    @WebEndpoint(name = "SueldoImpPort")
    public SueldoDao getSueldoImpPort() {
        return super.getPort(new QName("http://ws.upeu.edu.pe/", "SueldoImpPort"), SueldoDao.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SueldoDao
     */
    @WebEndpoint(name = "SueldoImpPort")
    public SueldoDao getSueldoImpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.upeu.edu.pe/", "SueldoImpPort"), SueldoDao.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SUELDOIMPSERVICE_EXCEPTION!= null) {
            throw SUELDOIMPSERVICE_EXCEPTION;
        }
        return SUELDOIMPSERVICE_WSDL_LOCATION;
    }

}
